services:
  vm:
    image: ssst0n3/docker_archive:kubernetes-v1.32.4_containerd-v2.0.4-calico_nerdctl-v2.0.4_v0.1.0
    environment:
      - "QEMU_NET=10.0.2.0/24"
      - "QEMU_DHCPSTART=10.0.2.16"
      - "QEMU_HOSTFWD=hostfwd=tcp::6443-:6443"
    ports:
        - "13244:22"
        - "13245:6443"
    tty: true
    stdin_open: true 

