services:
  master:
    image: swr.cn-south-1.myhuaweicloud.com/nebula-lab/docker_archive:cve-2020-8558-master_v0.1.0
  worker:
    image: swr.cn-south-1.myhuaweicloud.com/nebula-lab/docker_archive:cve-2020-8558-worker_v0.1.0
